proxy:
    http:
        addr: 127.0.0.1:8080
    https:
        addr: 127.0.0.1:8443
        params: 
            cert: server.cert
            key: server.key
    socks4: 
        addr: 127.0.0.1:1084
    socks5: 
        addr: 127.0.0.1:1080
    vpn: 
        addr: 127.0.0.1:1723
auth: 
    addr: plain://mikespook:123456
state: 
    addr: unix:///tmp/bur.sock
log: 
    level: all
